FROM python:3.11-slim-bullseye

# use bash shell.
ENV SHELL=/bin/bash

# define user variables for account setup.
ARG reldir=/root
ARG workdir=${reldir}/airkeys

RUN apt-get update && \
    apt-get --no-install-recommends -y install git \
    dos2unix \
    bash-completion \
    sudo \
    vim \
    openssh-server \
    make \
    build-essential cmake \
    wget unzip \
    libhdf5-103-1 libhdf5-dev \
    libopenblas0 libopenblas-dev \
    libprotobuf23 libprotobuf-dev \
    libjpeg62-turbo libjpeg62-turbo-dev \
    libpng16-16 libpng-dev \
    libtiff5 libtiff-dev \
    libwebp6 libwebp-dev \
    libopenjp2-7 libopenjp2-7-dev \
    libtbb2 libtbb-dev \
    libeigen3-dev \
    ffmpeg \
    libsm6 \
    libxext6 \
    libgl1 \
    python3-dev

# Start ssh client.
RUN service ssh start

# Configure sudo for initialization tasks. 
RUN echo "root ALL=(ALL) NOPASSWD: /bin/chown" >> etc/sudoers && \
    echo "root ALL=(ALL) NOPASSWD: /usr/bin/dos2unix" >> etc/sudoers


WORKDIR ${workdir}

# Copy source files
COPY . .

# Create virtaul env.
RUN python3 -m venv ${reldir}/env
ENV PATH=${reldir}/env/bin:$PATH
# Update Package Management
RUN pip3 install --upgrade pip
# Install all python modules.
RUN pip3 install -r config/requirements.txt

# Copy cli shortcuts for permanent use.

RUN sudo dos2unix ${workdir}/scripts/shortcuts.sh && \
    cp ${workdir}/scripts/shortcuts.sh ${reldir}/.bashrc



