name: Run Python Tests
on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    name: Setup and Run Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Build Dev Container & Run Tests
        uses: devcontainers/ci@v0.3
        with:
          subFolder: .devcontainer/python-dev
          imageName: python-container
          runCMD: test -a
          
      
