Data Conversion: {
    shape: class

    # Accepts frame data as 2D-Array of integers. Returns recolored 2D-Array of integers.
    colorMediapipe(Array*Integers* frame): "[][] Integer"
    colorCv(Array*Integers* frame): "[][] Integer"
}