Internal Clock : {
    shape : class

    - initTime : Parallel Thread

    - getSysTime(): Float
    getTime(): Float
    getTimeMs(): Integer
    createTimer(TimeLimit limit, Function task) : Timer
    createTimerMs(TimeLimit limit, Function task): Timer
}

Sequence Diagram : {
    shape : image
    icon : ./internal_clock.png
    width: 1200
    height: 1000
}
