Internal Clock : {
    shape : class

    - system clock : Parallel Thread

    getTime(): float
    createTimer(TimeLimit limit, Function task) : Timer
}

Sequence Diagram : {
    shape : image
    icon : ./internal_clock.png
    width: 1200
    height: 1000
}
