Internal Clock : {
    shape : class

    - system clock : Observer

    getTime(): float
    createTime(TimeLimit limit, Callback cb) 
}

Sequence Diagram : {
    shape : image
    icon : ./internal_clock.png
    width: 1200
    height: 1000
}
