Timer : {
    shape : class

    - startTime: Integer
    - limit: Integer

    getRemainingTime() : Float
    stop()
}

Normal Operation Sequence Diagram : {
    shape : image
    icon : ./timer_normal_operation.png
    width: 600
    height: 500
}

System Interrupt Sequence Diagram : {
    shape : image
    icon : ./timer_interrupt_operation.png
    width: 600
    height: 500
}