name: Run Python Tests
on:
  push:
    branches:
      - testing
  pull_request:
    branches:
      - testing

jobs:
  test:
    name: Setup and Run Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Node.js (Workaround)
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install devcontainer CLI
        run: npm install -g @devcontainers/cli

      - name: Start dev container
        run: devcontainer up --config .devcontainer/python-dev/devcontainer.json --workspace-folder .

      - name: Run tests in dev container
        run: devcontainer exec --config .devcontainer/python-dev/devcontainer.json --workspace-folder . test -a
          
      
