name: Run Python Tests
on:
  push:
    branches:
<<<<<<< HEAD
      - testing
  pull_request:
    branches:
      - testing
=======
      - develop
  pull_request:
    branches:
      - develop
>>>>>>> develop

jobs:
  test:
    name: Setup and Run Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      - name: Build Dev Container & Run Tests
        uses: devcontainers/ci@v0.3
        with:
<<<<<<< HEAD
=======
          subFolder: .devcontainer/python-dev
>>>>>>> develop
          imageName: python-container
          runCMD: test -a
          
      
